### ISSUE TITLE
Registration not working for the game

### ISSUE THREAD

**Issue by bilbon-s** [SAP-samples/devtoberfest-2021#11]
Hi, 
I registered 2 days ago but when going to the gameboard, I have a message stating that my community id is ok but I'm not registered yet. 
In eventbride my registration is ok and my community id is supplied.

Have a nice day
Sylvain

(note : the gameboard was ok the day I registered, but not anymore)

**Comment by jung-thomas** [comment]
The registrations are only uploaded in batches to the badge system once a week.  So it's normal that it will take a few days for registration to be visible on the Gameboard.
