### ISSUE TITLE
btp login --sso not working

### ISSUE THREAD

**Issue by Ennowulff** [SAP-samples/devtoberfest-2021#129]
hey there!
I am trying to solve this tutorial: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html

logging on via password did not work but I am not sure if copy-paste works properly and the password is quite long so that typing maybe was also wrong.
Tried out then sso option.

login in the browser successful. btp says "failed"... :(

![image](https://user-images.githubusercontent.com/75187288/137491582-68e31cc3-d2c6-48c0-9fc3-21333d879fd5.png)

What can I do?

**Comment by Ngugisenior** [comment]
i had the same issue 
in my case when entering the **global account subdomain** i was passing  **XXXXXXXXtrial** .
i changed it to **XXXXXXXXtrial-ga** and that worked

**Comment by qmacro** [comment]
Thanks @Ngugisenior ! Yes, it's important to distinguish between the account name and the subdomain associated with it. With trial accounts, for example, it's an easy relationship - the subaccount is just the account name suffixed with `-ga` as you point out.
