### ISSUE TITLE
How do contributions to the Open Documentation Initiative count

### ISSUE THREAD

**Issue by schmelto** [SAP-samples/devtoberfest-2021#13]
Due that changes in the Open Documentation Initiative are made in GitHub and are not connected to the SAP Cummunity ID how to report them that they are eligable for devtoberfest?

**Comment by jung-thomas** [comment]
When you submit a pull request to the Open Documentation initiative they ask you for your Community ID. That's how the existing Open Documentation badges are award.  There is nothing extra needed for Devtoberfest.  We are looking for the existing Open Documentation badge and if you get that awarded, we simply give you Devtoberfest points for that automatically.

**Comment by schmelto** [comment]
Thanks for clarifying!
