### ISSUE TITLE
Week 1 - Open source contribution

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAP-samples/devtoberfest-2021#142]
Good afternoon,
i've submited an open source contribution here https://github.com/AmauryVanEspen/OpenSAP-certification-API 
referenced here : https://github.com/SAP-samples/devtoberfest-2021/pull/76
unfortunately, it seems not being counted in the weekly challenge.
I had also suggest a pull request, I'm not able to find back about translation (according to this issue : https://github.com/SAP-docs/contribution-guidelines/issues/74)
Could you tell me more please ?
Thank you
Regards
Amaury

**Comment by jung-thomas** [comment]
We load the badges for the open source submissions manually once a week. I'll submit the next batch of them on Monday.
