### ISSUE TITLE
missing link in opensource.md

### ISSUE THREAD

**Issue by schmelto** [SAP-samples/devtoberfest-2021#15]
https://github.com/SAP-samples/devtoberfest-2021/blob/main/contest/opensource.md#entries

![image](https://user-images.githubusercontent.com/30869493/135645754-52a9e35a-d1b8-4b57-a967-f54dc306edbb.png)

for `here` no link is specified

**Comment by jung-thomas** [comment]
Sorry about that. I meant to take that line out until I have the job setup to generate a page off of the submissions like last year: https://github.com/SAP-samples/sap-devtoberfest-2020/blob/main/actions/build.js
I've not had a chance to update the script and test it for usage this year yet.  But maybe later today or this weekend and then I will add the reference and link back in.
