### ISSUE TITLE
I can't get the Badges and Points

### ISSUE THREAD

**Issue by ag3silaus** [SAP-samples/devtoberfest-2021#180]
Hello Guys,
Since my badges count has reached 99, my new badges are not appearing in your badges section (I'm getting a new badge earned mail) . Also, my scores on the Gameboard do not increase even though I have completed the 4th week's tasks.
I recently got this badge ("#403BED - Devtoberfest 2021 - Secure a Node.JS Application and Make It Available to Other Subaccounts)
This is my community ID "ag3silaus"
Regards
Burak

**Comment by ag3silaus** [comment]
Hi Thomas,

I'm facing the same problem again, this time it's stuck on 121 badges. I am getting "New Badge Earned" e-mail but i can't see in my Reputation.

Regards
Burak

**Comment by jung-thomas** [comment]
@ag3silaus - Thanks. I've reported it to the team responsible.
