### ISSUE TITLE
Week 6 Coding Challenge link broken

### ISSUE THREAD

**Issue by bmaciag** [SAP-samples/devtoberfest-2021#192]
Hi, 

the link to the Coding Challenge in Week 6 is not working. You can find it e.g. here:
https://github.com/SAP-samples/devtoberfest-2021/blob/main/topics/Week6_Frontend/README.md

Its leading to "https://github.com/SAP-samples/devtoberfest-2021-frontend-coding-challenge" which is not existing (404 error)

Best, Bart.

**Comment by jung-thomas** [comment]
@IObert - Do you want me to take the Coding Challenge repository public? It's still marked as private.

**Comment by IObert** [comment]
This was intentional as I wanted to wait until tomorrow when the first session “opens” the week. 
But as there are already some people interested, let's open the challenge now :)
