### ISSUE TITLE
About Week 6

### ISSUE THREAD

**Issue by ag3silaus** [SAP-samples/devtoberfest-2021#197]
Hello Developers,

i couldnt get my last points from 
"#A4BF5F - Devtoberfest 2021 - Develop a Vue Application for SAP BTP on Cloud Foundry"   and   
"#AE2D85 - Devtoberfest 2021 - Integrate Charts and Conditional Rendering"  
both of badges i already got and i can see under the Your Badges. But my points are still the same as my previous points

Regards
Burak

**Comment by jung-thomas** [comment]
Should be corrected now.  Sorry about that.
