### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by gmalew** [SAP-samples/devtoberfest-2021#198]
I have registered with SCNid grzegorz.malewski yesterday and got the order confirmation on Eventbrite, but Gameboard still says:
"Although you have entered a valid SAP Community ID and may even have
earned some Devtoberfest badges, it does not appear that you have
registered for Devtoberfest yet."

**Comment by jung-thomas** [comment]
We only upload and assign the badges for registration once a week. Your points will still accumulate but you won't be able to track them in the gameboard until the next upload of the badges.
