### ISSUE TITLE
About

### ISSUE THREAD

**Issue by JaroslawPeterko** [SAP-samples/devtoberfest-2021#199]
Hello Developers
I subbmited my simple project to list entry.csv, but I didn't recive badge  #2F243B - Devtoberfest 2021 - Project Submitted to GITHUB.
my profile : https://people.sap.com/jpeterko43

Could you help me?

thanks
Jaroslaw

**Comment by jung-thomas** [comment]
We have to assign those badges manually for the project submissions and only do so once a week. I see you submitted this two days ago.  We will do the final round of manual badge assignments this week before we do the final points calculation.
