### ISSUE TITLE
Gameboard not Updated

### ISSUE THREAD

**Issue by edwin7** [SAP-samples/devtoberfest-2021#206]
Hello Guys,

I've received #AE19A0 badge (Week 6 Coding Challenge). My new badge is also appearing in the badges section. But my score on the Game Board does not increase. My community id is "edwin_sendjaja34".

Regards,
Edwin
<img width="948" alt="Screenshot 2021-11-13 at 05 55 00" src="https://user-images.githubusercontent.com/709198/141588167-922bfee5-6880-4ccb-be39-2b0f1dc1eaeb.png">

**Comment by jung-thomas** [comment]
Thanks for catching that.  There was a slight difference in the badge name for that one badge compared to the JSON file we are using for points.  I've corrected this and the gameboard should be updated now. 

Welcome to Derdvana, BTW! Congrats.

**Comment by edwin7** [comment]
Thank you Thomas!
