### ISSUE TITLE
How do I know if I am eligible for prices ?

### ISSUE THREAD

**Issue by schmelto** [SAP-samples/devtoberfest-2021#209]
Hey there,

how do I know if I am eligible for prices like the tshirt, and which shipping address do you use if someone is eligible?

Kind regards
Tom

**Comment by jung-thomas** [comment]
You will be contacted by our marketing colleagues with the necessary information. There could be a little delay as there was, fortunately, a lot of people that reached levels to receive prizes.

**Comment by schmelto** [comment]
Thanks @jung-thomas

**Comment by schmelto** [comment]
Will there still be an email?

**Comment by jung-thomas** [comment]
Emails started going out yesterday.  Each one has an individual code so it's not a mass mailing and will take a little time for all of them to go out.
