### ISSUE TITLE
where will the Level 1,2,3 winners list be published?

### ISSUE THREAD

**Issue by adbeera** [SAP-samples/devtoberfest-2021#210]
In the closing section only one winner is being published. How about other levels.

**Comment by jung-thomas** [comment]
I don't know if we will publish all winners at all levels; but winners will be contacted directly soon with details.  Most of the team is just back from TechEd and we do have Thanksgiving here in the US this week -- so much of us are out this week.  But we will get everything pulled together as soon as possible.
