### ISSUE TITLE
Slovakia not on list of valid countries

### ISSUE THREAD

**Issue by softy12** [SAP-samples/devtoberfest-2021#211]
Hello,

would like to ask why Slovakia not on [list of valid countries ](https://github.com/SAP-samples/devtoberfest-2021/blob/main/TOC.md)?
It is a pity; I believe you may had a bunch of developers joining had it been otherwise. Not like me who joined but realized that my country is not on the list just now :)
Anyhow thanks for the #sapdevtoberfest initiative, I learned a lot.

cheers
m./

**Comment by jung-thomas** [comment]
In a few countries there are legal restrictions against such contests. But we also have limitations from the company that processes and ships all the prizes.  We tried to cover as many countries as we could; but global shipping, legal contest rules, etc is a messier business than one might think. We are always looking how we can expand coverage as much as possible.
