### ISSUE TITLE
Devtoberfest Registration 

### ISSUE THREAD

**Issue by muralidhar2796** [SAP-samples/devtoberfest-2021#52]
Hi Thomas,

I registered myself on October 7. I waited till this Friday upload to refresh. Unfortunately, my registration badge is still not visible. Am I missed out? :(
SCN id : muralidhar.2796

**Comment by frvdp** [comment]
Hi Thomas,

same problem. User name frvdp.

**Comment by muralidhar2796** [comment]
Thanks for the update!

**Comment by muralidhar2796** [comment]
got mine going as well! :) Thanks a lot Thomas 👍
