### ISSUE TITLE
btp CLI too new

### ISSUE THREAD

**Issue by se38** [SAP-samples/devtoberfest-2021#53]
Tutorial "Devtoberfest 2021 - Scavenger Hunt (#3F50A2)"
"Get Started with the SAP BTP Command Line Interface (btp CLI)"
"Step 6: Log in to your global account"

After starting the CLI I'm getting the following error:
```
Your client (2.10.0) is too new and not supported by the configured server (2.9.0).
Please download a client version 2.9.x from: https://tools.hana.ondemand.com/#cloud-btpcli
```
A client version 2.9.x is not available on the download site (only 2.8 and 2.10). 
With the version 2.8 it worked though. Maybe a hint on the tutorial page would be fine

**Comment by qmacro** [comment]
Thanks for bringing this to our attention @se38. I've added a note to Step 6 in the tutorial (see below) and also contacted the tutorial owner and team responsible for btp CLI. I'm sure they'll take a look first thing tomorrow, but in the meantime, perhaps the note will help people. I appreciate you logging this here! 

<img width="827" alt="screenshot 2021-10-10 at 08 15 35" src="https://user-images.githubusercontent.com/73068/136686516-32d2bf50-0730-4a32-806d-f27b412b8bff.png">

**Comment by davidsmith288** [comment]
I followed the advice to use v2.8.0 and got this error instead

C:\Users\i063230\Downloads>tar -xvzf btp-cli-windows-amd64-2.8.0.tar.gz
x windows-amd64/btp.exe

C:\Users\i063230\Downloads>cd windows-amd64

C:\Users\i063230\Downloads\windows-amd64>btp login --sso
The configuration at C:\Users\i063230\AppData\Local\SAP\btp\config.json was written for a client with version 2.10.0. The currently used client has version 2.8.0. Hence the configuration cannot be used

FAILED

**Comment by se38** [comment]
Hey David,
just delete the config.json.
Cheers, Uwe
