### ISSUE TITLE
Devtoberfest 2021 - Submit project to Devtoberfest GitHub

### ISSUE THREAD

**Issue by TinhToQuang** [SAP-samples/devtoberfest-2021#63]
Hi Thomas,

Could you please to let me know how and when the badge of activity "Submit project to Devtoberfest GitHub" will be visible in my SCN ID?

My SCN ID:  tinh.toquang

**Comment by jung-thomas** [comment]
We had not planned to grant those until the end of the event. However the response has been incredible - more submissions than last year even though it isn't the primary focus of this years contest. Therefore we might do a badge upload at the mid-point next week as well.
