### ISSUE TITLE
Gameboard not Updated 

### ISSUE THREAD

**Issue by rimjhim167** [SAP-samples/devtoberfest-2021#68]
I have updated my SCN profile( https://people.sap.com/rimjhim167), and have also registered for Devtoberfest 2021, last week.

I can see the Badges in my profile, but my gameboard is not updated yet.

Can you please look into the matter ?

**Comment by jung-thomas** [comment]
That's because you don't have the registration badge yet.  This is done in batches.  We are waiting for the batch from the end of last week to be uploaded still. I will double check yours after I received notification that the registration badge uploads has occurred.

**Comment by jung-thomas** [comment]
Your registration badge is now there. Have fun!
