### ISSUE TITLE
Gameboard not working with my id

### ISSUE THREAD

**Issue by CONCETO-flow** [SAP-samples/devtoberfest-2021#72]
Hi,

I can't check my progress on the gameboard with my id.

URL used:
https://devrel-tools-prod-scn-badges-srv.cfapps.eu10.hana.ondemand.com/devtoberfestContest/florian.wallburg

Error message:
```
Error: Server responded to https://people-api.services.sap.com/rs/
badge/florian.wallburg?sort=timestamp,desc&size=1000 with status code
500:
{"url":"https://people-api.services.sap.com/rs/badge/florian.wallburg"
,"message":"org.springframework.dao.
IncorrectResultSizeDataAccessException: Query { \"$java\" : Query: { \
"userName\" : \"florian.wallburg\"}, Fields: {}, Sort: {} } returned
non unique result.","id":"reputation.0","guid":"A11E5A98-A51E-4EC5-
B390-FD3A6EFD88D3","statusCode":500,"reason":"Internal Server Error."}
```

**Comment by jung-thomas** [comment]
@AmauryVanEspen  - I just tried with your ID and it works fine from both the people profile and the gameboard. https://devrel-tools-prod-scn-badges-srv.cfapps.eu10.hana.ondemand.com/devtoberfestContest/amauryvanespen

**Comment by AmauryVanEspen** [comment]
Thank you @jung-thomas it seems it works as well, I do not understand why it did not this morning with the same url.

**Comment by CONCETO-flow** [comment]
It's working now and my badges are also shown. Thank you.
