### ISSUE TITLE
game-specific-rules list not complete

### ISSUE THREAD

**Issue by schmelto** [SAP-samples/devtoberfest-2021#8]
https://github.com/SAP-samples/devtoberfest-2021/blob/main/contest/readme.md#game-specific-rules

In line [39](https://github.com/SAP-samples/devtoberfest-2021/blame/main/contest/readme.md#L39) the end of the sentence is missing.

**Comment by jung-thomas** [comment]
Thank you pointing that out.  Looks like a cut and paste error as that line was out of context. I've corrected.
